a04_practice/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

import polls.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', polls.views.index, name='index'),
    path('polls/', include('polls.urls')),
    path('rsvp/', include('rsvp.urls')),
]

a04_practice/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/detail', views.detail, name='detail'),
    path('<int:question_id>/vote', views.vote, name='vote'),
    path('<int:pk>/results', views.ResultsView.as_view(), name='results'),
]

a04_practice/rsvp/urls.py
from django.urls import path

from . import views

app_name = 'rsvp'
urlpatterns = [
    path('', views.index, name='index'),
]

a04_practice/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

a04_practice/rsvp/models.py
from django.db import models

# Create your models here.

a04_practice/rsvp/forms.py
from django import forms
from django.core.exceptions import ValidationError
import datetime


class RsvpForm(forms.Form):
    name = forms.CharField(
        max_length=10,
        label='your name',
        widget=forms.TextInput(
            attrs={
                'style': 'width:30%; border: 2px dashed red;: red;',
                'placeholder': 'full name',
            }))
    email = forms.EmailField(
        max_length=20,
        label='your email',
        widget=forms.TextInput(
            attrs={
                'style': 'width:30%; border: 3px dashed green;',
                'placeholder': 'valid email',
            }))
    arrival_date = forms.DateField(
        help_text='within next 3 days',
        widget=forms.DateInput(attrs={'type': 'date'}))
    feedback = forms.CharField(widget=forms.Textarea(
        attrs={
            'style': 'width:100%; border: 4px dashed blue;',
            'placeholder': 'your messages'
        }))

    def clean_arrival_date(self):
        data = self.cleaned_data['arrival_date']

        # check if in the past
        if data < datetime.date.today():
            raise ValidationError('cannot be in the past')

        if data > datetime.date.today() + datetime.timedelta(days=3):
            raise ValidationError('cannot be more than 3 days ahead')

        return data

a04_practice/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse

from .models import Question, Choice


def index(request):
    # return HttpResponse('polls index page')
    latest_question_list = Question.objects.order_by('-pub_date')[:2]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    # return HttpResponse('detail page.')
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'polls/detail.html', context)


def vote(request, question_id):
    # return HttpResponse('vote page')
    question = get_object_or_404(Question, pk=question_id)
    try:
        choice_selected = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context = {
            'question': question,
            'error_message': "you didn't select a choice",
        }
        return render(request, 'polls/detail.html', context)
    else:
        choice_selected.votes += 1
        choice_selected.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

a04_practice/rsvp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .forms import RsvpForm


def index(request):
    # return HttpResponse('rsvp index page')
    if request.method == 'POST':
        form = RsvpForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            arrival_date = form.cleaned_data['arrival_date']
            feedback = form.cleaned_data['feedback']
            context = {
                'fields': {
                    'name': name,
                    'email': email,
                    'arrival_date': arrival_date,
                    'feedback': feedback,
                }
            }
            return render(request, 'rsvp/thanks.html', context)
        else:
            # return HttpResponse('RSVP form is invalid')
            context = {'form': form}
            return render(request, 'rsvp/index.html', context)
    else:
        form = RsvpForm()
        context = {'form': form}
        return render(request, 'rsvp/index.html', context)

a04_practice/polls/templates/polls/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Cyber lab</title>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

a04_practice/polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% block body %}
    <h1>{{ question.question_text }}</h1>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form method="POST" action="{% url 'polls:vote' question.id %}">
        {% csrf_token %}
        {% for choice in question.choice_set.all|dictsort:"id" %}
            <input type="radio" name="choice"
                id="choice{{ forloop.counter }}"
                value="{{ choice.id }}"
            >
            <label for="choice{{ forloop.counter }}">
                {{ choice.choice_text }}
            </label><br>
        {% endfor %}
        <input type="submit" value="vote">
    </form>
{% endblock %}

a04_practice/polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% block body %}
<h2>available pages: admin, polls, rsvp</h2>
<h1>Polls</h1>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">
            <h2>{{ question.question_text }}</h2>
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>no question available</p>
{% endif %}

{% endblock %}

a04_practice/polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <script src="{% static 'polls/script.js' %}"></script>
{% endblock %}
{% block body %}
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all|dictsort:"id" %}
            <li>
                {{ choice.choice_text }}: {{ choice.votes}}
                vote{{ choice.votes|pluralize }}
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">
        vote again?
    </a>

    <form>
        <input id="task" type="text" placeholder="new task">
        <input id="submit" type="submit" value="add">
    </form>
    <ul id="tasks"></ul>
{% endblock %}

a04_practice/rsvp/templates/rsvp/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>RSVP</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

a04_practice/rsvp/templates/rsvp/index.html
{% extends "rsvp/base.html" %}
{% block body %}
<h1>RSVP</h1>
<form method="POST" action="{% url 'rsvp:index' %}">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div>
        {{ form.as_p }}
    </div>
    <input type="submit" value="response">
</form>
{% endblock %}

a04_practice/rsvp/templates/rsvp/thanks.html
{% extends "rsvp/base.html" %}

{% block body%}
<h2>
    <ul>
        {% for key, value in fields.items %}
        <li>
            {{ key }}: {{ value }}
        </li>

        {% endfor %}
    </ul>
</h2>
<h1>
    <a href="{% url 'rsvp:index' %}">
        RSVP again?
    </a>
</h1>
{% endblock %}